### ISSUE TITLE
`query.onSnapshot`: Error 4 (timeout/unavailable) when querying large collections

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-firestore#1040]
#### Environment details

  - OS: Darwin Kernel Version 19.4.0
  - Node.js version: 12, 14
  - npm version: 6.14.4
  - `@google-cloud/firestore` version: 3.7.4

#### Steps to reproduce

Query a large collection using `query.onSnapshot` on a slow network connection or large enough collection. In my case I open four queries for four distinct collections of ~35k documents, each ~100kBs in size. After ~90 seconds, ~40k documents fetched, an error occurs:

```
Error: Error 4: The datastore operation timed out, or the data was temporarily unavailable.
    at QueryWatch.onData (/my-project-path/node_modules/@google-cloud/firestore/build/src/watch.js:346:34)
    at PassThrough.<anonymous> (/my-project-path/node_modules/@google-cloud/firestore/build/src/watch.js:284:26)
    at PassThrough.emit (events.js:311:20)
    at PassThrough.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at PassThrough.Readable.push (_stream_readable.js:209:10)
    at PassThrough.Transform.push (_stream_transform.js:152:32)
    at PassThrough.afterTransform (_stream_transform.js:96:10)
    at PassThrough._transform (_stream_passthrough.js:46:3)
```

API response from `QueryWatch.onData`:

```
remove {
  targetIds: [ 1 ],
  targetChangeType: 'REMOVE',
  cause: {
    details: [],
    code: 4,
    message: 'The datastore operation timed out, or the data was temporarily unavailable.'
  },
  resumeToken: <Buffer >,
  readTime: null
}
```

**Comment by mad-it** [comment]
Im pretty sure the response to this will be to create a cursor and use `startAfter`.  https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L978

A small helper function I created a while back is the only way to retrieve large collections:

```ts

const streamAllDocuments = async (
  queue: AsyncQueue<firestore.DocumentSnapshot>,
  collection: string,
  select?: firestore.FieldPath[],
  filters?: Parameters<firestore.Query.prototype['where']>[],
): Promise<void> => {
  let lastSnapshot: firestore.DocumentSnapshot | undefined = undefined;
  let batchCounter = 0;

  const query = firestore().collection(collection);

  const queryWithFilters =
    filters === undefined
      ? query
      : filters.reduce(
          (acc, filter) => {
            return acc.where(filter[0], filter[1], filter[2]);
          },
          query as firestore.Query,
        );

  const queryWithSelect =
    select === undefined
      ? queryWithFilters
      : queryWithFilters.select(...select);

  const queryWithLimit = queryWithSelect.limit(BATCH_SIZE);

  while (true) {
    const queryWithOffset =
      lastSnapshot !== undefined
        ? queryWithLimit.startAfter(lastSnapshot)
        : queryWithLimit;

    const querySnapshots = await queryWithOffset.get();

    queue.push(querySnapshots.docs);

    batchCounter = batchCounter + querySnapshots.size;
    lastSnapshot = querySnapshots.docs[querySnapshots.docs.length - 1];

    if (querySnapshots.size < BATCH_SIZE) {
      break;
    }
  }
};
```

**Comment by merlinnot** [comment]
Thanks for sharing. Yes, cursors will work, but there are two issues:
- I don't have any guarantees for the speed of a network connection, other network traffic affecting the bandwidth, ability of the application itself to consume a certain amount of data (the process might be too busy to read all the data in time, having a 10 Gbps network card bandwidth doesn't guarantee that the download speed will be 10 Gbps) and so on, and so forth... - it makes it really hard to estimate how the queries should be split to actually work, seems to me like it should be handled in a different way, in the library/back end itself - hence the issue.
- I need to not only get the first snapshot, but also subsequent updates, which makes the implementation more complex than the example you have given.

I'll need to work around it somehow to ship the functionality I need, but I believe the issue should be addressed somehow, that's why I reported it.

**Comment by Luise8** [comment]
I'm getting this with firebase admin.

**Comment by cherylEnkidu** [comment]
Hi @Luise8 ,

Could you please open a new ticket with context in detail?
