### ISSUE TITLE
Invalid argument error now explaining what the error is

### ISSUE THREAD

**Issue by jakeleventhal** [googleapis/nodejs-firestore#1080]
#### Environment details

  - OS: 10.15.5 Beta (19F83c)
  - Node.js version: 13.7.0
  - npm version: 6.14.4
  - `@google-cloud/firestore` version:  3.7.5

#### Steps to reproduce

I am not sure how to reproduce, all I know is somewhere I am getting:
```
(node:41601) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: Request contains an invalid argument.
    at Object.callErrorFromStatus (/Users/jakeleventhal/myproj/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/jakeleventhal/myproj/node_modules/@grpc/grpc-js/src/client.ts:324:36)
    at Object.onReceiveStatus (/Users/jakeleventhal/myproj/node_modules/@grpc/grpc-js/src/client-interceptors.ts:439:34)
    at Object.onReceiveStatus (/Users/jakeleventhal/myproj/node_modules/@grpc/grpc-js/src/client-interceptors.ts:402:48)
    at Http2CallStream.outputStatus (/Users/jakeleventhal/myproj/node_modules/@grpc/grpc-js/src/call-stream.ts:228:22)
    at Http2CallStream.maybeOutputStatus (/Users/jakeleventhal/myproj/node_modules/@grpc/grpc-js/src/call-stream.ts:278:14)
    at Http2CallStream.endCall (/Users/jakeleventhal/myproj/node_modules/@grpc/grpc-js/src/call-stream.ts:262:12)
    at Http2CallStream.handleTrailers (/Users/jakeleventhal/myproj/node_modules/@grpc/grpc-js/src/call-stream.ts:398:10)
    at ClientHttp2Stream.emit (events.js:321:20)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:485:12)
    at emit (internal/http2/core.js:289:8)
    at processTicksAndRejections (internal/process/task_queues.js:87:22)
```

The issues are:
1. The error should include what the invalid argument is
2. The error should include the place in the code that the error occurred in the stack trace

**Comment by thebrianchen** [comment]
@jakeleventhal Thanks for filing the issue! The error you are receiving is from our backend, which does not include the invalid argument in its error. I'm currently looking into wrapping node errors to preserve the stack trace from the original call, which should hopefully help you trace down the original errors.
