### ISSUE TITLE
Documentation regarding onSnapshot is incomplete.

### ISSUE THREAD

**Issue by mad-it** [googleapis/nodejs-firestore#1090]
I have reached some undocumented behavior after deploying something to production that is not caught by the Firestore emulator or the SDK.

It looks like the `onSnapshot()` method of the Firestore SDK does not support `select`. 

```
Error: Error 3: 'select' clauses are not supported for real-time queries.
    at QueryWatch.onData (/run/node_modules/@google-cloud/firestore/build/src/watch.js:333:34)
    at PassThrough.<anonymous> (/run/node_modules/@google-cloud/firestore/build/src/watch.js:280:26)
    at PassThrough.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at PassThrough.Readable.push (_stream_readable.js:217:10)
    at PassThrough.Transform.push (_stream_transform.js:152:32)
    at PassThrough.afterTransform (_stream_transform.js:96:10)
    at PassThrough._transform (_stream_passthrough.js:46:3)
    at PassThrough.Transform._read (_stream_transform.js:191:10)
```

Is there any plans on supporting this in the future?

**Comment by schmidt-sebastian** [comment]
We currently don't have any plans to expose this functionality via `onSnapshot()` listeners. I will update our API documentation to highlight this.

**Comment by mad-it** [comment]
A bit more then half a year later. I would like to create a feature request for this :)

This feature would align the usage of `onSnapshot` and `get`.

**Comment by schmidt-sebastian** [comment]
@mad-it - Since this is backend issue, do you mind filing an issue at https://cloud.google.com/support/docs/issue-trackers? Thanks
