### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parent' of null

### ISSUE THREAD

**Issue by nbransby** [googleapis/nodejs-firestore#1098]
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'parent' of null
    at Function.forCollectionQuery (C:\Code\firebase\functions\node_modules\@google-cloud\firestore\build\src\reference.js:885:47)
    at new CollectionReference (C:\Code\firebase\functions\node_modules\@google-cloud\firestore\build\src\reference.js:1814:39)
    at DocumentReference.get parent [as parent] (C:\Code\firebase\functions\node_modules\@google-cloud\firestore\build\src\reference.js:179:16)
```

#### Environment details

  - OS: WIndows 10
  - Node.js version: v12.16.2
  - npm version: 6.14.4
  - `@google-cloud/firestore` version: 3.7.5

#### Steps to reproduce

````js
const doc =  (await firestore().collectionGroup('aSubcollection').limit(1).get())[0]
for(let ref = doc.ref; ref != null; ref = ref.parent) { }
````

**Comment by schmidt-sebastian** [comment]
@nbransby Thanks for reporting this. This is a pretty embarrassing bug that we will fix shortly. 

Please do note that we don't return an array for documents from `get()`, but rather a QuerySnapshot. You will have to use `(await query.get()).docs()[0]` once our fix is released.

**Comment by nbransby** [comment]
Of course sorry I wrote that snippet just for the example. 

Glad I could help
