### ISSUE TITLE
Firestore SDK does not play well with different versions of grpc-js installed

### ISSUE THREAD

**Issue by mad-it** [googleapis/nodejs-firestore#1233]
Firestore does not seem to play well with a different version of grpc-js installed. In the reproduction repository added below I installed grpc-js version `1.1.0` and immediately connection to the emulator stops working. 

Once you remove the grpc-js and run `npm dedupe` it start working again.

#### Environment details

  - OS: Linux
  - Node.js version: 12
  - npm version: 6.14.x
  - `@google-cloud/firestore` version: 3.8.6

#### Steps to reproduce

Here is a small repository with a reproduction. Run the latest Firestore emulator on port 4500 or adjust the test to run it on desired port.
https://github.com/mad-it/firestore-bug

The error:
```
jest --no-cache

 FAIL  src/index.spec.ts
  ✕ should work (115ms)

  ● should work

    TypeError: Channel credentials must be a ChannelCredentials object

      11 |   const ref = firestore.collection("test").doc();
      12 | 
    > 13 |   await ref.create({ foo: "foo" });
         |             ^
      14 | 
      15 |   const read = await ref.get();
      16 | 

      at new ChannelImplementation (node_modules/google-gax/node_modules/@grpc/grpc-js/src/channel.ts:150:13)
      at new Client (node_modules/google-gax/node_modules/@grpc/grpc-js/src/client.ts:146:30)
      at new ServiceClientImpl (node_modules/google-gax/node_modules/@grpc/grpc-js/src/make-client.ts:119:3)
      at GrpcClient.createStub (node_modules/google-gax/src/grpc.ts:290:18)
      Caused by: Error: 
      at WriteBatch.commit (node_modules/@google-cloud/firestore/build/src/write-batch.js:415:23)
      at DocumentReference.create (node_modules/@google-cloud/firestore/build/src/reference.js:283:14)
      at Object.<anonymous> (src/index.spec.ts:13:13)
```

**Comment by schmidt-sebastian** [comment]
@mad-it Thanks for providing the repro. 

This has already been fixed in the SDK and a release for this will go out today. The fix for this is here: https://github.com/googleapis/nodejs-firestore/commit/56355f1c83b055fdbd3ed47e069df813696a1fc0#diff-4de362b91cfe3cd8254c447a5a08b316R453
