### ISSUE TITLE
Setting isBrowser to false manually

### ISSUE THREAD

**Issue by dudizimber** [googleapis/nodejs-firestore#1264]
Hi,
I'm having a problem when using another package that redefines the `window` variable, even when running in a NodeJS envirnoment.
I'd like to ask if it is possible to add a feature where the user can set the variable `isBrowser` to false manually.

Thank you.

PS: I'm using this package as dependency to the `firebase-admin` package.

**Comment by schmidt-sebastian** [comment]
@dudizimber Thanks for filing this.

Can you point at the code you are referring to? We use `isBrowser` in the Firestore Web SDK, but not (at least not directly) in this SDK, which is bundled in firebase-admin. I suspect some layer underneath us might use similar functionality, but it would help if you could provide some pointers.

**Comment by dudizimber** [comment]
Hey @schmidt-sebastian, thanks for your reply.
The file I'm talking about is `@google-cloud\firestore\build\src\v1\firestore_client.js`.
![code](https://user-images.githubusercontent.com/16744955/87870974-76588e00-c9b5-11ea-8dc3-0da21ebc94ce.png)

Now I dove a little deeper, and it looks like the version of this package I'm using is 3.8.6, and the isBrowser check was removed in the 4.0.0 update I guess. 
For what I can conclude, the problem is that the package `firebase-admin` has `"@google-cloud/firestore": "^3.0.0"` as dependency. So I'm guessing that to solve this issue, they'd need to update `firebase-admin` to work with a newer version of `@google-cloud/firestore`.

I'm attaching the error I get when I try to create/update a document in Firestore:
`
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.basename (path.js:1289:5)
    at GrpcClient.loadProto (/workspace/node_modules/firebase-admin/node_modules/google-gax/build/src/grpc.js:117:29)
    at new FirestoreClient (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:118:38)
    at ClientPool.Firestore._clientPool.pool_1.ClientPool [as clientFactory] (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:329:26)
    at ClientPool.acquire (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/pool.js:87:35)
    at ClientPool.run (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/pool.js:164:29)
    at Firestore.request (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:983:33)
    at WriteBatch.commit_ (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/write-batch.js:496:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Caused by: Error
    at WriteBatch.commit (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/write-batch.js:415:23)
    at DocumentReference.set (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:341:14)
    at Function.saveOrganization (/workspace/lib/classes/Database.js:28:57)
    at createOrganization (/workspace/lib/controllers/organization.controller.js:56:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)"  
`

Thank you

**Comment by schmidt-sebastian** [comment]
@dudizimber Thanks for the pointer. The code you refer is to actually auto-generated, and as such I am not super familiar with its internals. That's why `isBrowser` didn't immediately ring a bell.

We have updated `firebase-admin` last week. If you update to version 9, you will be able to use the 4.x version of `@google-cloud/firestore`. Assuming that this solves your issue, I will close this. Please do comment if there is anything else we can help with.
