### ISSUE TITLE
[Firestore] firestore.settings() cannot have 'host' when FIRESTORE_EMULATOR_HOST is set

### ISSUE THREAD

**Issue by samtstern** [googleapis/nodejs-firestore#1265]
#### Environment details

  - OS: macOS
  - Node.js version: 10.x
  - npm version: 6.14.5
  - `@google-cloud/firestore` version: 4.1.1 (via `firebase-admin` 9.0.0)

#### Steps to reproduce

index.js
```js
const admin = require('firebase-admin');

admin.initializeApp({
  projectId: 'abc-123'
});

admin.firestore().settings({
  host: 'localhost:8080',
  ssl: false
});

console.log("Ok!");
```

```bash
$ node index.js 
Ok!
```

```bash
$ FIRESTORE_EMULATOR_HOST=localhost:8080 node index.js 
/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.4ukcSYBP/node_modules/@google-cloud/firestore/build/src/index.js:424
                throw new Error('Cannot set both "settings.host" and "settings.servicePath".');
                ^

Error: Cannot set both "settings.host" and "settings.servicePath".
    at Firestore.validateAndApplySettings (/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.4ukcSYBP/node_modules/@google-cloud/firestore/build/src/index.js:424:23)
    at Firestore.settings (/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.4ukcSYBP/node_modules/@google-cloud/firestore/build/src/index.js:413:14)
    at Object.<anonymous> (/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.4ukcSYBP/index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

`settings.host` should **override** the environment variable, and it definitely shouldn't throw if the values are the same in any case.

**Comment by samtstern** [comment]
cc @yuchenshi

**Comment by schmidt-sebastian** [comment]
@samtstern What is the rationale for `settings.host` to take precedence? It feels like it is more likely that someone has host configured and wants to temporarily override the setting via the environment variable. I can go either way, just want to check.

**Comment by thebrianchen** [comment]
I looked at the pub/sub emulator [code](http://google3/java/com/google/cloud/pubsub/testing/experimental/emulator/Main.java), and I couldn't seem to find any logic that dealt with environmental variable conflicts with user code. Regardless, I think it makes the most sense to have the user code override the environmental variable code. However, should we log a warning when we do so, or do you think it's unnecessary?

**Comment by samtstern** [comment]
@thebrianchen that sounds good to me, I agree explicit user code should win.  Having a warning if both are set *and they disagree* sounds like a good idea.

**Comment by thebrianchen** [comment]
Notes from a separate conversation:
Currently, the existing code prioritizes `FIRESTORE_EMULATOR_HOST` over user-code in the Firestore constructor. Changing to user code priority would be a breaking change, and having different priority orders in the Firestore constructor and `settings()` would make it confusing for developers. Thus, the plan is to remove the thrown error, but keep `FIRESTORE_EMULATOR_HOST` priority.
