### ISSUE TITLE
PERMISSION_DENIED executing quickstart.js

### ISSUE THREAD

**Issue by adeturner** [googleapis/nodejs-firestore#1297]
Hi,

I'm raising this here because its almost impossible to search the web for an answer, and maybe improving the readme a little might help future consumers...

I've created a plain vanilla Google Cloud Firestore... without Firebase (I didn't really want to go there because my architecture is SPA>Cloud Functions>Firestore)

Following https://cloud.google.com/firestore/docs/quickstart-servers?authuser=1#go_1  

I'm developing on my laptop with the server SDK trying to get the quick start to work here https://github.com/googleapis/nodejs-firestore

I setup a service account:
```
gcloud iam service-accounts create myserviceacct --display-name myserviceacct
gcloud projects add-iam-policy-binding myproj --member "serviceAccount:myserviceacct@myproj.iam.gserviceaccount.com" --role "roles/owner"

```
and downloaded the creds:

```
gcloud iam service-accounts keys create myserviceacct.json --iam-account myserviceacct@myproj.iam.gserviceaccount.com
export GOOGLE_APPLICATION_CREDENTIALS="myserviceacct.json"
```

Now I'm running the quickstart and getting an error

```
(node:7534) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: Missing or insufficient permissions.
    at Object.callErrorFromStatus (/home/ade/openAPI/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/ade/openAPI/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/home/ade/openAPI/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
    at Object.onReceiveStatus (/home/ade/openAPI/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
    at /home/ade/openAPI/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Caused by: Error
    at WriteBatch.commit (/home/ade/openAPI/node_modules/@google-cloud/firestore/build/src/write-batch.js:419:23)
    at DocumentReference.set (/home/ade/openAPI/node_modules/@google-cloud/firestore/build/src/reference.js:341:14)
    at quickstart (/home/ade/openAPI/firestore/1.js:16:18)
    at Object.<anonymous> (/home/ade/openAPI/firestore/1.js:36:1)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

I appreciate that the server SDK is meant to be used on GCP side, but in terms of development is there a pointer for working on a laptop?

Thanks, Adrian

$ npm version
{
  openapi: '0.0.1',
  npm: '6.14.8',
  ares: '1.16.0',
  brotli: '1.0.7',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.0.4',
  modules: '83',
  napi: '6',
  nghttp2: '1.41.0',
  node: '14.9.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.39.0',
  v8: '8.4.371.19-node.13',
  zlib: '1.2.11'
}

$ node --version
v14.9.0

**Comment by adeturner** [comment]
Did a little debugging without success... 

@google-cloud/firestore/build/src/v1/firestore_client.js 
constructor:
```
  // Save the auth object to the client, for use by other methods.
  this.auth = this._gaxGrpc.auth;

  auth={"jsonContent":null,"cachedCredential":null,"_cachedProjectId":"myproj","keyFilename":"./myproj-firestore.json",
  "scopes":["https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/datastore"]}
```

@google-cloud/firestore/build/src/v1/firestore_client.js 
commit():
```
  request={"database":"projects/apiv01/databases/(default)",
  "writes":[{"update":{"name":"projects/apiv01/databases/(default)/documents/posts/intro-to-firestore","fields":{"title":{"stringValue":"Welcome to Firestore"},"body":{"stringValue":"Hello World"}}}}]}
  option={"otherArgs":{"headers":{"google-cloud-resource-prefix":"projects/apiv01/databases/(default)",
  "x-goog-request-params":"database=projects%2Fmyproj%2Fdatabases%2F(default)"}},"retry":{"retryCodes":[10,14],
  "backoffSettings":{"initialRetryDelayMillis":100,"retryDelayMultiplier":1.3,"maxRetryDelayMillis":60000,"initialRpcTimeoutMillis":60000,
  "rpcTimeoutMultiplier":1,"maxRpcTimeoutMillis":60000,"totalTimeoutMillis":600000}}}
  callback=undefined
```

also tried adding some roles without luck:

```
gcloud projects get-iam-policy apiv01 \
--flatten="bindings[].members" \
--format='table(bindings.role)' \
--filter="bindings.members:myservacct@myproj.iam.gserviceaccount.com"

ROLE
roles/datastore.user
roles/datastore.owner
roles/owner

(node:5263) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: Missing or insufficient permissions.
```

**Comment by adeturner** [comment]
Wow, on a hunch I've solved it.

Steps
- I deleted the service account
- I discovered that doesn't remove the iam policy bindings
- I removed the iam policy bindings
- I recreated the service account
- I added the policy bindings
- I removed the credential file
- I recreated the credential file


```
gcloud iam service-accounts delete myserviceacct@myproj.iam.gserviceaccount.com
gcloud projects remove-iam-policy-binding myproj --member "serviceAccount:myserviceacct@myproj.iam.gserviceaccount.com" --role "roles/owner"
gcloud projects remove-iam-policy-binding myproj --member "serviceAccount:myserviceacct@myproj.iam.gserviceaccount.com" --role "roles/datastore.owner"
gcloud projects remove-iam-policy-binding myproj --member "serviceAccount:myserviceacct@myproj.iam.gserviceaccount.com" --role "roles/datastore.user"


gcloud iam service-accounts create myserviceacct --display-name myserviceacct
gcloud projects add-iam-policy-binding myproj --member "serviceAccount:myserviceacct@myproj.iam.gserviceaccount.com" --role "roles/owner"
gcloud projects add-iam-policy-binding myproj --member "serviceAccount:myserviceacct@myproj.iam.gserviceaccount.com" --role "roles/datastore.owner"

gcloud projects get-iam-policy myproj \
--flatten="bindings[].members" \
--format='table(bindings.role)' \
--filter="bindings.members:myserviceacct@myproj.iam.gserviceaccount.com"

ROLE
roles/datastore.owner
roles/owner


export GOOGLE_APPLICATION_CREDENTIALS=`pwd`/myserviceacct.json
rm $GOOGLE_APPLICATION_CREDENTIALS
gcloud iam service-accounts keys create ${GOOGLE_APPLICATION_CREDENTIALS} --iam-account myserviceacct@myproj.iam.gserviceaccount.com



node quickstart.js

Entered new data into the document
Updated an existing document
Read the document
Deleted the document
```
