### ISSUE TITLE
Race condition in documented counter implementation

### ISSUE THREAD

**Issue by toots** [googleapis/nodejs-firestore#160]
Hi,

There seems to be race conditions in the documented implementation of a counter using `runTransaction`. I've seen it in my own project in the update phase so I wrote a quick script to try to reproduce.

Documented counter is here: https://cloud.google.com/nodejs/docs/reference/firestore/0.12.x/Firestore#runTransaction

The code can be found here: https://github.com/toots/firestore-race-condition.  When running the script, one can see that the counter is created multiple times. Furthermore, later on multiple threads receives the same value. These two observations runs counter to the documented pessimistic lock that is supposed to be placed on the document once the first `get` request succeed:
```
% node ./index.js
[0] Thread starting..
[2] Thread starting..
[1] Thread starting..
[3] Thread starting..
[8] Thread starting..
[6] Thread starting..
[5] Thread starting..
[4] Thread starting..
[7] Thread starting..
[9] Thread starting..
[0] Creating counter..
[2] Creating counter..
[1] Creating counter..
[3] Creating counter..
[6] Got counter value: 1
[5] Got counter value: 1
[8] Got counter value: 1
[1] Got counter value: 1
[9] Got counter value: 1
[7] Got counter value: 1
[2] Got counter value: 2
[3] Got counter value: 2
[4] Got counter value: 2
[5] Got counter value: 2
[8] Got counter value: 2
[1] Got counter value: 3
[9] Got counter value: 3
[7] Got counter value: 3
[5] Got counter value: 3
[2] Got counter value: 3
[8] Got counter value: 3
[3] Got counter value: 4
[1] Got counter value: 4
[7] Got counter value: 4
[8] Got counter value: 5
[5] Got counter value: 5
[2] Got counter value: 5
[1] Got counter value: 6
[7] Got counter value: 6
[8] Got counter value: 7
[2] Got counter value: 7
Worker errored: Error: Too much contention on these documents. Please try again.
    at /private/tmp/firestore-race-condition/node_modules/@google-cloud/firestore/node_modules/grpc/src/client.js:554:15
Worker errored: Error: Too much contention on these documents. Please try again.
    at /private/tmp/firestore-race-condition/node_modules/@google-cloud/firestore/node_modules/grpc/src/client.js:554:15
```

Tested with package version `0.12.0` and `0.13.0`

**Comment by schmidt-sebastian** [comment]
The code within `runTransaction` is retried on contention. You should not write any logic that relies on how often it is executed. My guess as what to is happening here is that your transactions fail to commit, and hence we re-run your code, which explains the additional logging output. To determine whether a transaction was committed correctly, you can modify your code as such:

```
 return firestore.runTransaction(function (transaction) {
    var documentRef = firestore.doc(input.counter);
    return transaction.get(documentRef).then(function (doc) {
      if (doc.exists) {
        var count =  doc.get("count") || 0;
        if (count >= input.maxCount) {
          return Promise.resolve(count);
        }
        transaction.update(documentRef, { count: ++count });
        return Promise.resolve(count);
      }

      transaction.create(documentRef, { count: 1 });
      return Promise.resolve(1);
    });
  }).then(count => {
    console.log('Updated counter to ' + count);
  });

```

Please let us know if this helped resolve your issue.

**Comment by toots** [comment]
Hoo, tricky.

Okay, I've updated my test code and it seems to be working as expected now. I'm gonna revisit my application's logic.

Thanks for your valuable response. It would be nice if the doc could include this information!
