### ISSUE TITLE
Fatal Bug

### ISSUE THREAD

**Issue by cavedweller** [googleapis/nodejs-firestore#1763]
When I deploy the firebase functions it throws this error:
```
node_modules/@google-cloud/firestore/types/firestore.d.ts:117:29 - error TS1005: ']' expected.


117     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                ~~

node_modules/@google-cloud/firestore/types/firestore.d.ts:117:48 - error TS1005: ';' expected.

117     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                   ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:117:50 - error TS1109: Expression expected.

117     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                     ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:117:51 - error TS1109: Expression expected.

117     {[K in keyof T & string as `${Prefix}.${K}`]+?: T[K]};
                                                      ~

node_modules/@google-cloud/firestore/types/firestore.d.ts:2278:1 - error TS1128: Declaration or statement expected.

2278 }
```
I have googled myself into an oblivion, I cant find a fix.

I have upgraded and downgraded my typescript versions 

current package.json

```
{
  "name": "functions",
  "version": "1.0.0",
  "description": "",
  "main": ".eslintrc.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint \"src/**/*\"",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/cavedweller/Firebase_Functions.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/cavedweller/Firebase_Functions/issues"
  },
  "homepage": "https://github.com/cavedweller/Firebase_Functions#readme",
  "engines": {
    "node": "12"
  },
  "dependencies": {
    "@angular/fire": "^7.4.1",
    "@firebase/storage": "^0.9.9",
    "@google-cloud/tasks": "^3.0.2",
    "@sendgrid/mail": "^7.7.0",
    "axios": "^0.21.4",
    "dateformat": "^4.6.3",
    "firebase": "^9.9.3",
    "firebase-admin": "^11.0.1",
    "firebase-functions": "^3.22.0",
    "node-fetch": "^2.6.7",
    "typescript": "^4.0.5"
  },
  "devDependencies": {
    "@types/babel__core": "^7.1.19",
    "@typescript-eslint/eslint-plugin": "^5.35.1",
    "@typescript-eslint/parser": "^5.35.1",
    "eslint": "^8.23.0",
    "eslint-plugin-import": "^2.26.0",
    "firebase-functions-test": "^2.3.0"
  },
  "private": true
}
```

The only reason why I am running typescript version 4.0.5 is because it is the only version that shows where the issue is, the later versions just say that there is a bug and don't point me to the issue.

I have deleted my node_modules, package-lock.json and package.json about 10 times. Nothing works 

Any assistance would greatly be appreciated

**Comment by tom-andersen** [comment]
If you run `npm update`, you will see that you are using `4.8.2` as of this writing. I recommend pinning to `~4.7.4`.

We have a known issue with `4.8.2` type checking in this library, and will be doing the same in our `package.json`.

**Comment by cavedweller** [comment]
Hi @tom-andersen, thank you for the response.

So I think I have really messed up something.

When I create a new package.jsonit changed the "main" , when I deploy the functions now it says the functions have deployed but I cannot see them in my project, in fact it says "The following functions are found in your project but do not exist in your local source code" then prompts me to delete the function, which I did but it does not upload anything after.

```
{
  "name": "functions",
  "version": "1.0.0",
  "description": "",
  "main": ".eslintrc.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint \"src/**/*\"",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/cavedweller/Firebase_Functions.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/cavedweller/Firebase_Functions/issues"
  },
  "homepage": "https://github.com/cavedweller/Firebase_Functions#readme",
  "engines": {
    "node": "12"
  },
  "dependencies": {
    "@angular/fire": "^7.4.1",
    "@firebase/storage": "^0.9.9",
    "@google-cloud/tasks": "^3.0.2",
    "@sendgrid/mail": "^7.7.0",
    "axios": "^0.21.4",
    "dateformat": "^4.6.3",
    "firebase": "^9.9.3",
    "firebase-admin": "^11.0.1",
    "firebase-functions": "^3.22.0",
    "node-fetch": "^2.6.7",
    "typescript": "^4.7.4"
  },
  "devDependencies": {
    "@types/babel__core": "^7.1.19",
    "@typescript-eslint/eslint-plugin": "^5.35.1",
    "@typescript-eslint/parser": "^5.35.1",
    "eslint": "^8.23.0",
    "eslint-plugin-import": "^2.26.0",
    "firebase-functions-test": "^2.3.0"
  },
  "private": true
}
```

I then changed my "main" back to what it was before I deleted the package.json. It now prompts me with this error - "Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation."

```
{
  "name": "functions",
  "main": "lib/index.js",
  "scripts": {
    "lint": "eslint \"src/**/*\"",
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "12"
  },
  "dependencies": {
    "@firebase/storage": "^0.9.9",
    "@google-cloud/tasks": "^3.0.2",
    "@sendgrid/mail": "^7.7.0",
    "axios": "^0.21.4",
    "dateformat": "^4.6.3",
    "firebase-admin": "^11.0.1",
    "firebase-functions": "^3.22.0",
    "node-fetch": "^2.6.7",
    "typescript": "^4.7.4"
  },
  "devDependencies": {
    "@types/babel__core": "^7.1.19",
    "@typescript-eslint/eslint-plugin": "^5.35.1",
    "@typescript-eslint/parser": "^5.35.1",
    "eslint": "^8.23.0",
    "eslint-plugin-import": "^2.26.0",
    "firebase-functions-test": "^2.3.0"
  },
  "private": true
}
```

Any assistance would greatly be appreciated 😎

**Comment by tom-andersen** [comment]
Note the use of caret `^` instead of tilde `~` in `package.json`.

You have to use `~`, otherwise it will simply retrieve the latest version when you run `npm update` or the first time you run `npm install`.

**Comment by cavedweller** [comment]
@tom-andersen , I truly am grateful for the responses.

So I changed the `^` to `~` for the typescript package.
I then ran update and install to double sure everything was loaded 

Updated package.json
```
 "dependencies": {
    "@firebase/storage": "^0.9.9",
    "@google-cloud/tasks": "^3.0.2",
    "@sendgrid/mail": "^7.7.0",
    "axios": "^0.21.4",
    "dateformat": "^4.6.3",
    "firebase-admin": "^11.0.1",
    "firebase-functions": "^3.22.0",
    "node-fetch": "^2.6.7",
    "typescript": "~4.7.4"
  },
```

The error I have is still the same 

```
Function failed on loading user code. This is likely due to a bug in the user code. Error message: Error: please examine your function logs to see the error cause: https://cloud.google.com/functions/docs/monitoring/logging#viewing_logs. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.

Functions deploy had errors with the following functions:
        tw(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions
```

I have had a look at the firebase function logs and this is the output

```
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/workspace/node_modules/firebase-admin/lib/default-namespace.js:19:30)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) 
```

Thank you again for your assistance 👌

**Comment by cavedweller** [comment]
What I landed up doing was running firebase init and just resetting everything, it loaded the necessary versions and it seems to be working again.

Thanks again for your assistance

**Comment by ee99ee** [comment]
I can confirm reproduction of this issue and that pegging to typescript `~4.7.4` resolved it for me.
