### ISSUE TITLE
Intermittent problem initializing Timestamp from milliseconds

### ISSUE THREAD

**Issue by willbattel** [googleapis/nodejs-firestore#1810]
#### Environment details

  - OS: Firebase Cloud Functions
  - Node.js version: 18
  - `@google-cloud/firestore` version: 6.4.1 (via `firebase-admin` 11.4.1)
  - `luxon` version: 3.2.1 (shouldn't be the culprit here but including for posterity)

#### Steps to reproduce

I have the following cloud function that creates Firestore documents for new users in Firebase Auth.

```
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import * as functions from 'firebase-functions'
import { DateTime } from 'luxon';

export const createUserDocument = functions.auth.user().onCreate(async (user) => {
    const timestamp = Timestamp.fromMillis(DateTime.fromHTTP(user.metadata.creationTime).toMillis())
    const userRef = getFirestore().collection('users').doc(user.uid)
    // Create user document...
})
```

For some reason, we're getting `Error: Value for argument "seconds" is not a valid integer.` when trying to create the Timestamp. I have verified the inputs to the constructor:
- `user.metadata.creationTime` = `Sat, 07 Jan 2023 14:04:12 GMT`
- `DateTime.fromHTTP(user.metadata.creationTime).toMillis()` = `1673100252000`

Full stack trace: 
```
 Error: Value for argument "seconds" is not a valid integer.
    at validateInteger (/workspace/node_modules/@google-cloud/firestore/build/src/validate.js:201:19)
    at new Timestamp (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:73:40)
    at Timestamp.fromMillis (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:135:16)
    at /workspace/lib/createUserDocument.js:9:45
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/cloud-functions.js:79:23)
    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:144:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

However, **we seem to only get this issue on our deployed cloud function**...running this code locally on my macOS machine with the same package versions and UTC string seems to work as expected. We are trying to determine whether this happens for all executions on Cloud Functions, or only some. I will update this when I have that information.

Let me know if this would be more appropriate for the `firebase-admin` repo, or cloud functions for that matter. This one is a bit of a head scratcher.

**Comment by willbattel** [comment]
After digging a little deeper this looks like it's due to odd behavior from `firebase-admin` passing the `creationTime` in a different format on the deployed functions, so the `DateTime` object becomes `null` with causes the error we see here. Apologies for not finding this sooner 🙃
