### ISSUE TITLE
Error: read ECONNRESET at TLSWrap.onStreamRead

### ISSUE THREAD

**Issue by maylorsan** [googleapis/nodejs-firestore#1952]
#### Error Details
Since November 15, we have encountered error code ECONNRESET a total of 733 times across different functions in our production project, including HTTP, event-based, and scheduled functions. Each instance of this error is linked to the get method in @google-cloud/firestore. Below are excerpts from our error logs.

#### Environment Details
Operating System: `macOS Sonoma 14.0`
Node.js Version: `v16.20.0`
npm Version: `v8.19.4`
@google-cloud/firestore Version: `v6.6.0` (used with firebase-admin `v11.9.0`)

#### Additional Context
- Our setup does not utilize the `preferRest` option in Firestore configurations.
- 99% of the code where this error appears has not been changed recently.
- We've observed a significant shift in our 'worst-case' scenario execution times. Previously, our 99th percentile of requests completed within an average of 0.94 seconds. This metric has since increased, with the current 99th percentile finishing below 4.3 seconds.

#### Steps to Reproduce
This error is not consistently reproducible and appears only in our production environment. It has not been observed in our local development setup. The sporadic nature of this issue in the production environment makes it challenging to diagnose and resolve. Here are some specific instances from our cloud functions' logs:

```
ERROR 2023-11-16T04:00:05.224945Z Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
DEFAULT 2023-11-16T04:00:05.224955Z Caused by: Error
DEFAULT 2023-11-16T04:00:05.224962Z at Query._get (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:1717:23)
DEFAULT 2023-11-16T04:00:05.224967Z at Query.get (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:1705:21)
DEFAULT 2023-11-16T04:00:05.224972Z at Object.getSomeDataFromFirestore (/workspace/dist/src/DB/db.js:226:14)
DEFAULT 2023-11-16T04:00:05.224976Z at /workspace/dist/src/someService/controllers/someFunction.js:13:51
DEFAULT 2023-11-16T04:00:05.224981Z at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/cloud-functions.js:75:23)
DEFAULT 2023-11-16T04:00:05.224986Z at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:141:25
DEFAULT 2023-11-16T04:00:05.224990Z at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```
ERROR 2023-11-24T09:05:00.290480Z Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
DEFAULT 2023-11-24T09:05:00.290490Z Caused by: Error
DEFAULT 2023-11-24T09:05:00.290497Z at AggregateQuery._get (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:2425:23)
DEFAULT 2023-11-24T09:05:00.290503Z at AggregateQuery.get (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:2414:21)
DEFAULT 2023-11-24T09:05:00.290509Z at Object.getSomeDataByFirestore (/workspace/dist/src/DB/db.js:625:70)
DEFAULT 2023-11-24T09:05:00.290514Z at someFunction (/workspace/dist/src/someService/controller/someFunction.js:12:27)
DEFAULT 2023-11-24T09:05:00.290517Z eventBasedCloudFunction execution finished
DEFAULT 2023-11-24T09:05:00.290519Z at runMicrotasks (<anonymous>)
DEFAULT 2023-11-24T09:05:00.290525Z at processTicksAndRejections (node:internal/process/task_queues:96:5) {
DEFAULT 2023-11-24T09:05:00.290529Z errno: -104,
DEFAULT 2023-11-24T09:05:00.290534Z code: 'ECONNRESET',
DEFAULT 2023-11-24T09:05:00.290538Z syscall: 'read'
DEFAULT 2023-11-24T09:05:00.290542Z }
```

```
ERROR 2023-12-04T19:49:22.100953Z Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
DEFAULT 2023-12-04T19:49:22.100966Z Caused by: Error
DEFAULT 2023-12-04T19:49:22.100983Z at Firestore.getAll (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:1013:23)
DEFAULT 2023-12-04T19:49:22.100990Z at DocumentReference.get (/workspace/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:230:32)
DEFAULT 2023-12-04T19:49:22.100995Z at Object.findUserByID (/workspace/dist/src/DB/db.js:40:14)
DEFAULT 2023-12-04T19:49:22.101001Z at someFunction (/workspace/dist/src/someService/controllers/someFunction.js:20:44)
DEFAULT 2023-12-04T19:49:22.101007Z at /workspace/dist/src/framework/express/middlewares/express-handler.js:18:42
DEFAULT 2023-12-04T19:49:22.101012Z at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)
DEFAULT 2023-12-04T19:49:22.101017Z at next (/workspace/node_modules/express/lib/router/route.js:144:13)
DEFAULT 2023-12-04T19:49:22.101022Z at validateFirebaseToken (/workspace/dist/src/framework/firebase/auth/validateFirebaseToken.js:20:9)
DEFAULT 2023-12-04T19:49:22.101027Z at runMicrotasks (<anonymous>)
DEFAULT 2023-12-04T19:49:22.101032Z at processTicksAndRejections (node:internal/process/task_queues:96:5) {
DEFAULT 2023-12-04T19:49:22.101037Z errno: -104,
DEFAULT 2023-12-04T19:49:22.101041Z code: 'ECONNRESET',
DEFAULT 2023-12-04T19:49:22.101046Z syscall: 'read'
DEFAULT 2023-12-04T19:49:22.101050Z }
```

**Comment by ehsannas** [comment]
Thanks for reporting @maylorsan. As @cherylEnkidu said, the way to look further into it would be to look at server logs that requires filing a cloud support ticket.

In the meantime, would you also be able to log the `process.env.FIRESTORE_PREFER_REST` environment variable in your cloud function? If this is set to true, then your client is in fact using `preferRest`.

I _think_ the default value of this env var was [going through some changes](https://github.com/googleapis/nodejs-firestore/issues/1943#issuecomment-1809369245). In the meantime, you can explicitly set the env var to your desired value to avoid the default value being set for you.

**Comment by cherylEnkidu** [comment]
Hi,

Since you are not running into this issue anymore, I will close this ticket for now. Please feel free to reopen it if you have any questions.
