### ISSUE TITLE
Using document set function, got Error: 5 NOT_FOUND

### ISSUE THREAD

**Issue by hankdesu** [googleapis/nodejs-firestore#2012]
- What you're trying to do
 I was trying to integrate firebase into Nuxt3 server api and following the instruction from official document. Then I was at the step of [Add Data](https://firebase.google.com/docs/firestore/quickstart?hl=en&authuser=0&_gl=1*niy9*_up*MQ..*_ga*MTQ3NTg0NjYwNy4xNzEwMjIzMjk4*_ga_CW55HF8NVT*MTcxMDIyMzI5OC4xLjEuMTcxMDIyMzcyOS4xMS4wLjA.#add_data), but I got Error: 5 NOT_FOUND. After searched relative information, still couldn't solve this problem. 
- What code you've already tried
**Environment:**
  - OS: macOS Sonoma 14.3.1
  - Node Version: v20.11.0
  - NPM Version: v10.2.4
  - Package.json: `"firebase-admin": "^12.0.0",
    "nuxt": "^3.10.3",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"`

  **Code**:
```javascript
import path from 'path';
import fs from 'fs';
import { initializeApp, applicationDefault, cert } from 'firebase-admin/app';
import { getFirestore, Timestamp, FieldValue, Filter } from 'firebase-admin/firestore';

export default defineEventHandler(async (event) => {
    try {
        const config = useRuntimeConfig(event);
        const filePath = path.resolve(process.cwd(), config.firebaseKey)
        const serviceAccount = JSON.parse(fs.readFileSync(filePath, 'utf-8'))
        initializeApp({ credential: cert(serviceAccount) })

        const db = getFirestore();
        const docRef = db.collection('/users').doc('alovelace');

        await docRef.set({
        first: 'Ada',
        last: 'Lovelace',
        born: 1815
        });
        return 'hello';
    } catch (error) {
        throw error;
    }
});

```
- Any error messages you're getting
```bash
error:  Error: 5 NOT_FOUND:
    at callErrorFromStatus (/Users/hank/help-u-focus/node_modules/@grpc/grpc-js/src/call.ts:82:17)
    at Object.onReceiveStatus (/Users/hank/help-u-focus/node_modules/@grpc/grpc-js/src/client.ts:360:55)
    at Object.onReceiveStatus (/Users/hank/help-u-focus/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
    at Object.onReceiveStatus (/Users/hank/help-u-focus/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at <anonymous> (/Users/hank/help-u-focus/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/hank/help-u-focus/node_modules/@grpc/grpc-js/src/client.ts:325:42)
    at ServiceClientImpl.<anonymous> (/Users/hank/help-u-focus/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at /Users/hank/help-u-focus/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:239:29
    at /Users/hank/help-u-focus/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/Users/hank/help-u-focus/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at /Users/hank/help-u-focus/node_modules/google-gax/build/src/normalCalls/retries.js:119:13
    at OngoingCallPromise.call (/Users/hank/help-u-focus/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/Users/hank/help-u-focus/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /Users/hank/help-u-focus/node_modules/google-gax/build/src/createApiCall.js:108:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Caused by: Error
    at WriteBatch.commit (/Users/hank/help-u-focus/node_modules/@google-cloud/firestore/build/src/write-batch.js:433:23)
    at DocumentReference.set (/Users/hank/help-u-focus/node_modules/@google-cloud/firestore/build/src/reference.js:403:27)
    at Object.handler (/Users/hank/help-u-focus/server/api/hello.get.js:16:1)
    at file:///Users/hank/help-u-focus/node_modules/h3/dist/index.mjs:1890:43
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (file:///Users/hank/help-u-focus/node_modules/h3/dist/index.mjs:1962:19)
    at async Server.toNodeHandle (file:///Users/hank/help-u-focus/node_modules/h3/dist/index.mjs:2249:7) {
  code: 5,
  details: '',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

**Comment by hankdesu** [comment]
It's working now. I'm not sure which step resulted in the creation of a new second project in Google Cloud. However, when I used the service account key from this new second project, everything started functioning properly.

Yesterday, I was troubleshooting an error prompted by the firebase-admin module. Following the guidance, I navigated to the Google Cloud platform, created a new project, and assigned a service account key. But it didn't work.

Today, when I navigated to the Firebase console > project settings > service accounts tab, I suddenly noticed there was a new second project. Eventually, using the service account key from this new project resolved the issue.
