### ISSUE TITLE
Error: Argument "data" is not a valid Document. Input is not a plain JavaScript object.

### ISSUE THREAD

**Issue by Spazer9** [googleapis/nodejs-firestore#213]
#### Environment details

  - OS: Windows 10
  - Node.js version: 8.11.1
  - npm version:  5.6.0
  - `@google-cloud/firestore` version: 0.14.1

#### Steps to reproduce

I'm unable to create any document, Firestore keeps throwing an error that the object i'm providing is not a POJO although I've tried on the console with the simplest object i can make `{ foo: 'bar'}`

My code is pretty simple at this point:

```
const Firestore = require('@google-cloud/firestore');

const firestore = new Firestore({
  projectId: process.env.GCLOUD_PROJECT_ID,
  credentials: {
    private_key: process.env.GCLOUD_PRIVATE_KEY,
    client_email: process.env.GCLOUD_CLIENT_EMAIL
  },
});

const doc = firestore.doc('posts/intro-to-firestore')
doc.set({ foo: 'bar' })
```

The error's instantly thrown (maybe has to do with some TS firestore uses?)

```
Error: Argument "data" is not a valid Document. Input is not a plain JavaScript object.
    at Object.exports.(anonymous function) [as isDocument] (C:\Users\space\Dropbox\apps\fire\node_modules\@google-cloud\firestore\src\validate.js:86:15)
    at WriteBatch.set (C:\Users\space\Dropbox\apps\fire\node_modules\@google-cloud\firestore\src\write-batch.js:286:14)
    at DocumentReference.set (C:\Users\space\Dropbox\apps\fire\node_modules\@google-cloud\firestore\src\reference.js:420:8
 at repl:1:24
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at REPLServer.defaultEval (repl.js:242:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound (domain.js:314:12)
```

I've tried an empty `{}` and still doesn't work. Strangely `doc.set(Object.create(null))` works?!

**Comment by Spazer9** [comment]
It seems this is more of an Adonis problem. I was testing this whole time through their repl. but on regular Node repl it works fine. 

Still not sure why though.

**Comment by schmidt-sebastian** [comment]
This should not happen with the vanilla Node JS Server SDK. I am glad you figured out what was going on. Sorry for trouble!
