### ISSUE TITLE
trying to add a document with a number type property fails

### ISSUE THREAD

**Issue by aviv1ron1** [googleapis/nodejs-firestore#336]
version: 0.16.1
Trying to add a document with a number type in the property, for example: `{ test: 1 }` fails.
stack trace:
`TypeError: util.Long.fromValue is not a function
 at Type.Value$fromObject [as fromObject] (eval at Codegen (X:\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:18:29)
    at Type.fromObject (X:\node_modules\google-gax\node_modules\protobufjs\src\type.js:538:25)
    at Type.Document$fromObject [as fromObject] (eval at Codegen (X:\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:17:28)
    at Type.fromObject (X:\node_modules\google-gax\node_modules\protobufjs\src\type.js:538:25)
    at Type.Write$fromObject [as fromObject] (eval at Codegen (X:\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:10:21)
    at Type.fromObject (X:\node_modules\google-gax\node_modules\protobufjs\src\type.js:538:25)
    at Type.CommitRequest$fromObject [as fromObject] (eval at Codegen (X:\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:17:24)
    at Type.fromObject (X:\node_modules\google-gax\node_modules\protobufjs\src\type.js:538:25)
    at serialize (X:\node_modules\grpc\src\protobuf_js_6_common.js:70:23)
    at Object.final_requester.sendMessage (X:\node_modules\grpc\src\client_interceptors.js:802:37)`

code to reproduce: any code that adds a new document to a collection.
for example: `db.collection('health').add({ "test": 1 })`

**Comment by colombotapps** [comment]
I've had trouble before with the Long type in grpc being overwritten by another module in node_modules. It would only happen on a specific project, even though the dependency occurred in multiple projects. The problem dependency was long, which will add itself to the global environment and really old versions  (< 2.1.0) do not have a fromValue method. This version was being imported from a previous version of cassandra-driver. I had to look into package-lock.json to find it and "fixed it" by changing the long version by hand.

**Comment by schmidt-sebastian** [comment]
Can you try @colombotapps's suggestion? Please re-open this issue if this does not fix your problem.
