### ISSUE TITLE
Issue with @google-cloud/firestore@2.3.0

### ISSUE THREAD

**Issue by aaaguirrep** [googleapis/nodejs-firestore#764]
Hello,

I am experimenting the next issue with @google-cloud/firestore@2.3.0 and nodejs 12.10. I installed 2.2.9 and it worked.

**Code**
```
let subscriberOther = await db.collectionGroup('users').where('email', '==', req.email).get()
subscriberOther.forEach(doc => {
        subscriberId = doc.data().subscriber
        userDisplayName = doc.data().displayName,
	userRole = doc.data().roleId,
	owner = doc.data().owner
})
```

**Error**
`(node:1348) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Root.load (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\protobufjs\src\root.js:192:44)
    at Root.loadSync (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\protobufjs\src\root.js:235:17)
    at Object.loadSync (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\@grpc\proto-loader\build\src\index.js:230:27)
    at GrpcClient.loadFromProto (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\google-gax\build\src\grpc.js:118:44)
    at GrpcClient.loadProto (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\google-gax\build\src\grpc.js:145:21)
    at new FirestoreClient (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\@google-cloud\firestore\build\src\v1\firestore_client.js:112:32)
    at ClientPool.clientFactory (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\@google-cloud\firestore\build\src\index.js:315:26)
    at ClientPool.acquire (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\@google-cloud\firestore\build\src\pool.js:64:35)
    at ClientPool.run (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\@google-cloud\firestore\build\src\pool.js:121:29)
    at Firestore.readStream (C:\Users\ARSENIO\Desktop\Development\application\dev\backend\node_modules\@google-cloud\firestore\build\src\index.js:1000:26)
(node:1348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Regards,
Arsenio

**Comment by merlinnot** [comment]
I have a solution for you, but I'd leave the issue open, as it affects almost all Google libraries and should be fixed upstream.

The solution is as follows:
- remove node_modules
- remove package-lock.json
- npm install

**Comment by schmidt-sebastian** [comment]
@aaaguirrep Thanks for filing this issue and sorry to hear about your trouble! Unfortunately, there is an incompatibility if a new version of Firestore is used together with an older version of `google-gax`. We should have avoided this by releasing this as part of a major version bump, but we failed to realize this until after the release. 

For now, to make sure that you get the newest version, please follow the steps as outlined in your latest comment.

**Comment by manwithsteelnerves** [comment]
We see this issue with latest version of Admin 8.13.

```
Error: not supported
        at Root.loadSync (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/protobufjs/src/root.js:246:15)
        at Object.loadSync (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/@grpc/proto-loader/build/src/index.js:217:29)
        at GrpcClient.loadFromProto (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/google-gax/src/grpc.ts:151:40)
        at GrpcClient.loadProto (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/google-gax/src/grpc.ts:185:17)
        at new FirestoreClient (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:118:38)
        at ClientPool.Firestore._clientPool.pool_1.ClientPool [as clientFactory] (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:326:26)
        at ClientPool.acquire (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/pool.js:87:35)
        at ClientPool.run (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/pool.js:164:29)
        at Firestore.request (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:983:33)
        at WriteBatch.commit_ (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/write-batch.js:496:48)
    Caused by: Error: 
        at WriteBatch.commit (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/write-batch.js:415:23)
        at DocumentReference.set (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/reference.js:341:14)
        at FirestoreStandardDatabase.create (/Volumes/Work/Projects/Products/Platforms//Backend/FirebaseProject/functions/src/common/systems/database/providers/firestore-standard/firestore-standard-database.provider.ts:73:45)
```

Can someone suggest proper way to fix the gprc errors on every update?

**Comment by schmidt-sebastian** [comment]
Do you directly depend on `google-gax` or any other Google library besides Firestore?

**Comment by manwithsteelnerves** [comment]
@schmidt-sebastian  We use pubsub, cloud tasks as well. Let me share my package.json
```
"dependencies": {
    "@google-cloud/firestore": "^4.1.1",
    "@google-cloud/functions-framework": "^1.6.0",
    "@google-cloud/pubsub": "^2.2.0",
    "@google-cloud/storage": "^5.1.2",
    "@google-cloud/tasks": "^2.1.0",
    "@google-cloud/trace-agent": "^5.1.0",
    "@types/axios": "^0.14.0",
    "@types/cors": "^2.8.5",
    "@types/dotenv": "^6.1.1",
    "@types/express": "^4.17.7",
    "@types/faker": "^4.1.12",
    "@types/http-errors": "^1.8.0",
    "@types/lodash.chunk": "^4.2.6",
    "@types/morgan": "^1.9.1",
    "@types/nanoid": "^2.1.0",
    "@types/node-fetch": "^2.5.7",
    "@types/uuid": "^3.4.9",
    "axios": "^0.19.2",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-async-router": "^0.1.15",
    "firebase-admin": "^8.13.0",
    "firebase-functions": "^3.8.0",
    "google-auth-library": "^6.0.5",
    "lodash.chunk": "^4.2.0",
    "max-listeners-exceeded-warning": "0.0.1",
    "morgan": "^1.10.0",
    "nanoid": "^2.1.11",
    "node-fetch": "^2.6.0",
    "npm": "^6.14.6",
    "openapi-validator-middleware": "^3.0.1",
    "pubsub-js": "^1.8.0",
    "razorpay": "^2.0.6",
    "require-benchmark": "^1.0.0",
    "require-so-slow": "^2.0.2",
    "uuid": "^3.4.0"
  },
  "devDependencies": {
    "@firebase/app": "^0.6.8",
    "@firebase/testing": "^0.19.6",
    "@types/jest": "^25.2.3",
    "@types/node": "^13.13.14",
    "@types/sharp": "^0.25.0",
    "@types/shortid": "0.0.29",
    "@types/supertest": "^2.0.10",
    "cross-env": "^7.0.2",
    "faker": "^4.1.0",
    "fs-extra": "^9.0.1",
    "google-play-scraper": "^7.1.3",
    "jest": "^25.5.4",
    "jest-extended": "^0.11.5",
    "jest-stare": "^1.27.0",
    "sharp": "^0.25.4",
    "ts-essentials": "^6.0.7",
    "ts-jest": "^25.5.1",
    "ts-node": "^8.10.2",
    "tslint": "^6.1.2",
    "typescript": "^3.8.9"
  },
```

**Comment by schmidt-sebastian** [comment]
Please update to `firebase-admin` v9 as the first step. That should remove on duplicate copy of `@google-cloud/firestore`.

**Comment by manwithsteelnerves** [comment]
@schmidt-sebastian  Unfortunately, I don't see any difference. Still its throwing the same error.
On another note, upgrading to v9 gave this warning
```
npm WARN firebase-functions@3.8.0 requires a peer of firebase-admin@^8.0.0 but none is installed. You must install peer dependencies yourself.
```

But I see 3.8 is the latest though.

**Comment by schmidt-sebastian** [comment]
I am not sure how to solve your initial issue. It seems strange that you would run into this problem with every upgrade.

Regarding the warning in firebase-functions - we are working on releasing a new version that will bump the dependency to firebase-admin v9. For now, I would advise to just ignore the warning.
