### ISSUE TITLE
TypeError: setInterval(...).unref is not a function

### ISSUE THREAD

**Issue by 1amageek** [googleapis/nodejs-firestore#783]
#### Environment details

  - OS: macOS 10.15
  - Node.js version: v10.16.3
  - npm version: 6.9.0
  - `@google-cloud/firestore` version: 2.4.0

#### Steps to reproduce

This problem occurs when running tests using Jest.

```
    TypeError: setInterval(...).unref is not a function

      at new SubchannelPool (node_modules/@grpc/grpc-js/build/src/subchannel-pool.js:55:36)
      at Object.<anonymous> (node_modules/@grpc/grpc-js/build/src/subchannel-pool.js:99:30)
      at Object.<anonymous> (node_modules/@grpc/grpc-js/build/src/channel.js:21:27)
      at Object.<anonymous> (node_modules/@grpc/grpc-js/build/src/index.js:22:19)
      at Object.<anonymous> (node_modules/google-gax/src/grpc.ts:36:1)
      at Object.<anonymous> (node_modules/google-gax/src/index.ts:32:1)
      at Object.<anonymous> (node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:16:13)
      at Object.<anonymous> (node_modules/@google-cloud/firestore/build/src/v1/index.js:15:25)
      at Function.get (node_modules/@google-cloud/firestore/build/src/index.js:1154:18)
      at ClientPool.Firestore._clientPool.pool_1.ClientPool [as clientFactory] (node_modules/@google-cloud/firestore/build/src/index.js:315:45)
      at ClientPool.acquire (node_modules/@google-cloud/firestore/build/src/pool.js:64:35)
      at ClientPool.run (node_modules/@google-cloud/firestore/build/src/pool.js:121:29)
      at Firestore.request (node_modules/@google-cloud/firestore/build/src/index.js:962:33)
      at WriteBatch.commit_ (node_modules/@google-cloud/firestore/build/src/write-batch.js:448:14)
```

### Dependency
```json
  "dependencies": {
  },
  "devDependencies": {
    "@firebase/testing": "^0.13.0",
    "@types/jest": "^24.0.18",
    "@types/node": "^12.7.4",
    "firebase-admin": "^8.6.0",
    "jest": "^24.8.0",
    "ts-jest": "^24.0.2",
    "tslint": "^5.19.0",
    "typescript": "^3.6.2"
  },
  "peerDependencies": {
    "firebase-admin": "^8.6.0"
  },
  "resolutions": {},
  "jest": {
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
```

```typescript
import * as firebase from 'firebase-admin'

const secret = require("./secret.json")
firebase.initializeApp({
    credential: firebase.credential.cert(secret)
})

describe("Batch", () => {

	test("set test", async () => {
		const batch = firebase.firestore().batch()
		batch.set(firebase.firestore().collection("test").doc("doc"), {"a": "a"})
		await batch.commit()
	}, 10000)

})
```

Do test
```
jest 
```

**Comment by bcoe** [comment]
@1amageek I might be worth also logging an issue with Jest and referencing this issue, ` setInterval(() => {}, 100).unref()` is part of the Node.js runtime, and shouldn't be raising an exception.

**Comment by azymnis** [comment]
@1amageek FYI take a look at this comment https://github.com/facebook/jest/issues/9033#issuecomment-541310639

**Comment by schmidt-sebastian** [comment]
The references issue suggests to use `jest --env node` to run the tests. If this does not work for you, please do let us know. In the meantime, I am closing this issue as it does not seem specific to this library. Please do let us know if there are any changes we need to make.
