### ISSUE TITLE
[Bug] Unable to add documents to subcollections using the functions shell

### ISSUE THREAD

**Issue by DeveloperUX** [googleapis/nodejs-firestore#799]
I can't seem to be able to `add` data to subcollections in firestore using the functions shell emulator

#### Environment details

  - OS: Mac OS Catalin
  - Node.js version: v8.15.0
  - npm version: 6.7.0
  - `@google-cloud/firestore` version: "firebase-admin": "8.7.0"

#### Steps to reproduce

  1. Create a simple script that you can run in Firebase shell (ex):
```
admin.initializeApp({...});
const db = admin.firestore();

const run = async () => {
  await db.collection('papers')
      .doc(docId)
      .collection('pens')
      .add({x: 'a'});
};
run();
```
  2. Run the above script through the emulator (ex):
```
firebase functions:shell < script.js
```

**Expected Result:**
This code should run without any issues and add the object `{x: 'a'}` to the `pens` subcollection

**Actual Result:**
This code fails when run through the functions:shell but runs fine when added as a cloud function and run through the cloud function

**Error Stack**
```
(node:90760) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'constructor' of null
    at extractBaseClassName (/.../functions/node_modules/@google-cloud/firestore/build/src/validate.js:35:33)
    at Object.customObjectMessage (/.../functions/node_modules/@google-cloud/firestore/build/src/validate.js:55:26)
    at Object.validateDocumentData (/.../functions/node_modules/@google-cloud/firestore/build/src/write-batch.js:608:36)
    at CollectionReference.add (/.../functions/node_modules/@google-cloud/firestore/build/src/reference.js:1765:23)
    at runB (repl:43:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Stackoverflow Question:
https://stackoverflow.com/questions/59013268/unable-to-add-new-documents-to-a-collection-in-firestore-using-functionsshell

**Comment by DeveloperUX** [comment]
I'm guessing this has been recorded as a bug considering that the "bug" label was added. Looking forward to the fix. If I can help let me know

**Comment by bcoe** [comment]
@schmidt-sebastian any thoughts on this one?

**Comment by schmidt-sebastian** [comment]
@DeveloperUX This does not reproduce for me. I wonder if this might be caused by a package that is rewriting some parts of the prototype chain. For what it is worth, the input `{x: 'a'}` should not even invoke `customObjectMessage()`.

```
export function validateDocumentData(
  arg: string | number,
  obj: unknown,
  allowDeletes: boolean
): void {
  if (!isPlainObject(obj)) { 
    throw new Error(customObjectMessage(arg, obj));  // This should be true
  }
  ...
}

function isPlainObject(input: unknown): input is DocumentData {
  return (
   Object.prototype.toString.call(input) === '[object Object]' &&
    (Object.getPrototypeOf(input) === Object.prototype ||
      Object.getPrototypeOf(input) === null)
  );
}

```

`isPlainObject({x: 'a'})` returns true for me.

Can you send us a small self-contained reproduction (including your package.json) so we can investigate further?

**Comment by schmidt-sebastian** [comment]
Closing this due to inactivity. We can re-open this issue if we receive a repro.

**Comment by puppybits** [comment]
I've run into the same issue. `Object.getPrototypeOf(input) === Object.prototype` is the problem.

When edit that line of code in serializer.js in my node_modules to log out `Object.getPrototypeOf(input) === Object.prototype` it returns false. But when I log the exact same line in my own project's code it returns true.

**Comment by schmidt-sebastian** [comment]
Fix is coming!
