### ISSUE TITLE
can not get collections docs

### ISSUE THREAD

**Issue by koba1108** [googleapis/nodejs-firestore#806]
#### Environment details
- OS: Mac OS 10.15.1（19B88）
- Node.js version: v10.15.1
- npm version: 6.13.1
- firebase-admin: 8.8.0

#### Steps to reproduce

```
    const cols = await firestore().collectionGroup('col_name').get()
```

when this code runed display error like this.

```
/node_modules/@google-cloud/firestore/build/src/timestamp.js:86
     * as the given date.
                       ^

SyntaxError: Unexpected identifier
    at DestroyableTransform._transform (/node_modules/@google-cloud/firestore/build/src/reference.js:1504:52)
    at DestroyableTransform.Transform._read (/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at BunWrapper.ondata (internal/streams/legacy.js:15:31)
    at BunWrapper.emit (events.js:189:13)
    at BunWrapper.EventEmitter.emit (domain.js:441:20)
    at BunWrapper.<anonymous> (/node_modules/bun/node_modules/readable-stream/lib/_stream_readable.js:786:14)
    at BunWrapper.emit (events.js:194:15)
    at BunWrapper.EventEmitter.emit (domain.js:441:20)
    at /node_modules/bun/node_modules/readable-stream/lib/_stream_readable.js:803:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

if this code runed.
display this console log.

```
    const cols = await firestore().collectionGroup('col_name')
    console.log(cols)
```

```
Query {
  _firestore: Firestore {
    _settings: {
      credentials: [Object],
      projectId: 'xxxxxxxx',
      firebaseVersion: '8.8.0',
      libName: 'gccl',
      libVersion: '2.6.1 fire/8.8.0'
    },
    _settingsFrozen: false,
    _serializer: Serializer {
      createReference: [Function],
      timestampsInSnapshots: true
    },
    _projectId: 'xxxxxxxx',
    _lastSuccessfulRequest: 0,
    _preferTransactions: false,
    _clientPool: ClientPool {
      concurrentOperationLimit: 100,
      clientFactory: [Function],
      activeClients: Map {}
    }
  },
  _queryOptions: QueryOptions {
    parentPath: ResourcePath {
      segments: []
    },
    collectionId: 'xxxxxxxx',
    allDescendants: true,
    fieldFilters: [],
    fieldOrders: [],
    startAt: undefined,
    endAt: undefined,
    limit: undefined,
    offset: undefined,
    projection: undefined
  },
  _serializer: Serializer {
    createReference: [Function],
    timestampsInSnapshots: true
  }
}
```

**Comment by schmidt-sebastian** [comment]
@koba1108 Thanks for the report! Can you share your `package.json` and/or a small reproduction? 
It would also help if you enabled logging (via `setLogFunction`) and shared your logs.

**Comment by koba1108** [comment]
@schmidt-sebastian 
thank you response!!

#### package.json
```
  "dependencies": {
    "@google-cloud/storage": "4.1.3",
    "@nuxtjs/apollo": "4.0.0-rc18",
    "@nuxtjs/auth": "4.8.4",
    "@nuxtjs/axios": "5.8.0",
    "@nuxtjs/moment": "1.4.0",
    "@sendgrid/client": "6.4.0",
    "@sendgrid/mail": "6.4.0",
    "apollo-cache-inmemory": "1.6.3",
    "apollo-link": "1.2.13",
    "apollo-link-http": "1.5.16",
    "axios": "0.19.0",
    "buefy": "0.8.8",
    "bulma-quickview": "2.0.0",
    "bulma-timeline": "3.0.4",
    "body-parser": "1.19.0",
    "core-js": "2.6.5",
    "cookie-parser": "1.4.4",
    "cookie-universal-nuxt": "2.0.19",
    "express": "4.17.1",
    "firebase": "7.5.1",
    "firebase-admin": "8.8.0",
    "graphql": "14.5.8",
    "graphql-tag": "2.10.1",
    "json2csv": "4.5.4",
    "moment": "2.24.0",
    "moment-timezone": "0.5.27",
    "node-sass": "4.12.0",
    "nuxt": "2.10.2",
    "nuxt-buefy": "0.3.19",
    "sass-loader": "7.1.0"
  },
```

#### Add  setLogFunction code.
```
const express = require('express')
const router = express.Router()
const firebaseAdmin = require('firebase-admin')
const FIREBASE_SERVICE_ACCOUNT_KEY_PATH = 'xxxxxxxxxxxxxx'
firebaseAdmin.initializeApp({
  credential: firebaseAdmin.credential.cert(FIREBASE_SERVICE_ACCOUNT_KEY_PATH)
})
const { firestore } = firebaseAdmin
firestore.setLogFunction(console.log)

router.get('/', async function(req, res, next) {
  try {
    const chatRooms = await firestore().collectionGroup('chat_rooms')
    const docs = await chatRooms.get()
  } catch (e) {
    console.error(e)
  }
})

```

#### Firestore logs

```
Firestore (2.6.1) 2019-12-07T05:06:56.774Z ##### [Firestore]: Initialized Firestore                                                                                                                       14:06:56
Firestore (2.6.1) 2019-12-07T05:06:56.777Z ES0zB [ClientPool.acquire]: Creating a new client                                                                                                              14:06:56
Firestore (2.6.1) 2019-12-07T05:06:56.994Z ##### [Firestore]: Initialized Firestore GAPIC Client                                                                                                          14:06:56
Firestore (2.6.1) 2019-12-07T05:06:56.996Z ES0zB [Firestore.readStream]: Sending request: {"parent":"projects/xxxxxxxxx/databases/(default)/documents","structuredQuery":{"from":[{"collectionId":"xxxxxxxxx","allDescendants":true}]}}
Firestore (2.6.1) 2019-12-07T05:06:57.978Z ES0zB [Firestore.readStream]: Received response: {"document":{"fields":{"latest_message_path":{"stringValue":"xxxxxxxxx/xxxxxxxxx/xxxxxxxxx/xxxxxxxxx","valueType":"stringValue"},"latest_sent_user_id":{"stringValue":"xxxxxxxxx","valueType":"stringValue"},"latest_sent_at":{"timestampValue":{"seconds":"1556270620","nanos":0},"valueType":"timestampValue"},"type":{"stringValue":"support","valueType":"stringValue"},"created_at":{"timestampValue":{"seconds":"1556270617","nanos":747000000},"valueType":"timestampValue"},"members":{"mapValue":{"fields":{"xxxxxxxxx":{"booleanValue":true,"valueType":"booleanValue"},"xxxxxxxxx":{"booleanValue":true,"valueType":"booleanValue"}}},"valueType":"mapValue"},"latest_message":{"stringValue":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","valueType":"stringValue"}},"name":"projects/xxxxxxxxx/databases/(default)/docuseconds":"1556270618","nanos":124031000},"updateTime":{"seconds":"1570244382","nanos":96703000}},"transaction":{"type":"Buffer","data":[]},"readTime":{"seconds":"1575695217","nanos":864605000},"skippedResults":0}
Firestore (2.6.1) 2019-12-07T05:06:57.979Z ES0zB [Firestore._initializeStream]: Releasing stream                                                                                                          14:06:57
/node_modules/@google-cloud/firestore/build/src/timestamp.js:86
     * as the given date.
                       ^
```

**Comment by schmidt-sebastian** [comment]
Sorry, this does not reproduce for me, even with the dependencies you listed. If you can provide a small reproducible example, then we can take another look.
