### ISSUE TITLE
Firestore bandwidth exhausted issue

### ISSUE THREAD

**Issue by hadi-10** [googleapis/nodejs-firestore#939]
We are using cloud firestore as our database and getting following error when rate of parallel reads from database increases.

    details:  "Bandwidth exhausted"    
    message:  "8 RESOURCE_EXHAUSTED: Bandwidth exhausted"    
    stack:  "Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
    at callErrorFromStatus (/usr/service/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/usr/service/node_modules/@grpc/grpc-js/build/src/call.js:79:34)
    at Http2CallStream.emit (events.js:198:15)
    at process.nextTick (/usr/service/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)"    

We couldn't find what is the rate limits. Could you please let me know what are the read rate limits and in which cases firestore returns Bandwidth exhausted error?

Note: Billing is enabled in our project. The problem is we can't find what limit we are reaching.

**Comment by schmidt-sebastian** [comment]
@hadi-10 Do you mind filing a support ticket? Our backend team can look at your exact traffic patterns. Thank you!

https://cloud.google.com/support-hub
